name: Deploy wiki with docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      env:
        DOCS_PATH: ${{ vars.DOCS_PATH }}
        MKDOCS_PATH: ${{ vars.MKDOCS_PATH }}
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SERVER_PORT }}
        envs: DOCS_PATH,MKDOCS_PATH
        script: |
            cd "$DOCS_PATH" || exit

            # Mise à jour du dépôt de doc
            git pull origin main

            cd "$MKDOCS_PATH" || exit

            # Mise à jour du dépôt de doc
            git pull origin main
              
            # Destruction des anciens conteneurs et suppression de l'ancienne image
            docker-compose -f docker-compose.prod.yml down --rmi all || true
              
            # Construction de la nouvelle image et lancement du conteneur de build
            docker-compose -f docker-compose.prod.yml up --build